// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYMbkENozN23b0Tmg8j7rR0y-BPBXopHI',
    appId: '1:1087733691593:web:49522ca7e5e8ec38864918',
    messagingSenderId: '1087733691593',
    projectId: 'mobilestorefirebase',
    authDomain: 'mobilestorefirebase.firebaseapp.com',
    storageBucket: 'mobilestorefirebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcBfI7-vNsuUnMX0YswN7XVfPVSnRX8xo',
    appId: '1:1087733691593:android:4b6228da0e763caf864918',
    messagingSenderId: '1087733691593',
    projectId: 'mobilestorefirebase',
    storageBucket: 'mobilestorefirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_FpnLRdghRXEtDSnmtlkNGruF8G5hWvU',
    appId: '1:1087733691593:ios:0216276a1025a4b8864918',
    messagingSenderId: '1087733691593',
    projectId: 'mobilestorefirebase',
    storageBucket: 'mobilestorefirebase.firebasestorage.app',
    iosBundleId: 'com.codex.finance.financeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_FpnLRdghRXEtDSnmtlkNGruF8G5hWvU',
    appId: '1:1087733691593:ios:0216276a1025a4b8864918',
    messagingSenderId: '1087733691593',
    projectId: 'mobilestorefirebase',
    storageBucket: 'mobilestorefirebase.firebasestorage.app',
    iosBundleId: 'com.codex.finance.financeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYMbkENozN23b0Tmg8j7rR0y-BPBXopHI',
    appId: '1:1087733691593:web:74ad05550fbf20c8864918',
    messagingSenderId: '1087733691593',
    projectId: 'mobilestorefirebase',
    authDomain: 'mobilestorefirebase.firebaseapp.com',
    storageBucket: 'mobilestorefirebase.firebasestorage.app',
  );
}
