// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5rYyiS6COnG6tqgWXbnlJMYE3_pYfGXQ',
    appId: '1:34788182639:web:63c98e6986e771c3d75b9a',
    messagingSenderId: '34788182639',
    projectId: 'maliyati-app-2026',
    authDomain: 'maliyati-app-2026.firebaseapp.com',
    storageBucket: 'maliyati-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAeWKBMOK93Y2xcrji0pwTt0358DIUvn4',
    appId: '1:34788182639:android:033205b23cc63d31d75b9a',
    messagingSenderId: '34788182639',
    projectId: 'maliyati-app-2026',
    storageBucket: 'maliyati-app-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz5DWyGsoofu7bsTs9aqDlb3sXWbOYbvE',
    appId: '1:34788182639:ios:57002760caf5c608d75b9a',
    messagingSenderId: '34788182639',
    projectId: 'maliyati-app-2026',
    storageBucket: 'maliyati-app-2026.firebasestorage.app',
    iosBundleId: 'com.codex.finance.financeTracker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz5DWyGsoofu7bsTs9aqDlb3sXWbOYbvE',
    appId: '1:34788182639:ios:57002760caf5c608d75b9a',
    messagingSenderId: '34788182639',
    projectId: 'maliyati-app-2026',
    storageBucket: 'maliyati-app-2026.firebasestorage.app',
    iosBundleId: 'com.codex.finance.financeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5rYyiS6COnG6tqgWXbnlJMYE3_pYfGXQ',
    appId: '1:34788182639:web:5c0e88a83404b54ed75b9a',
    messagingSenderId: '34788182639',
    projectId: 'maliyati-app-2026',
    authDomain: 'maliyati-app-2026.firebaseapp.com',
    storageBucket: 'maliyati-app-2026.firebasestorage.app',
  );
}
